const translations = {
    'Create task': 'Crear tarea',
    'Create collapsed sub-process': 'Crear subproceso colapsado',
    'Create start event': 'Crear evento de inicio',
    'Create end event': 'Crear evento de fin',
    'Create gateway': 'Crear compuerta',
    'Create intermediate/boundary event': 'Crear evento intermedio/límite',
    'Create data object reference': 'Crear objeto de datos',
    'Create data store reference': 'Crear almacén de datos',
    'Create pool/participant': 'Crear pool/participante',
    'Activate create/remove space tool': 'Activar herramienta para crear/eliminar espacio',
    'Create group': 'Crear grupo',
    'Append Task': 'Agregar tarea',
    'Append EndEvent': 'Agregar evento de fin',
    'Append Gateway': 'Agregar compuerta',
    'Append intermediate/boundary event': 'Agregar evento intermedio/límite',
    'Change type': 'Cambiar tipo',
    'Delete': 'Eliminar',
    'Activate global connect tool': 'Activar herramienta de conexión global',
    'Activate hand tool': 'Activar herramienta de mano',
    'Activate lasso tool': 'Activar herramienta de selección',
    'Activate the space tool': 'Activar herramienta de espacio',
    'Tool': 'Herramienta',
    'Events': 'Eventos',
    'Activities': 'Actividades',
    'Gateways': 'Compuertas',
    'Artifacts': 'Artefactos',
    'Data objects': 'Objetos de datos',
    'Pools': 'Pools',
    'General': 'General',
    'Name': 'Nombre',
    'Id': 'Identificador',
    'Documentation': 'Documentación',
    'Version Tag': 'Versión',
    'Executable': 'Ejecutable',
    'Element documentation': 'Documentación del elemento',
    'Start Event': 'Evento de inicio',
    'create': 'Crear',
    'Extension properties': 'Extensiones',
    'Value': 'Valor',
    'empty': ''

};
export default translations;